# stats available at
# https://ci.appveyor.com/project/strukturag/libheif
image: Visual Studio 2019
configuration: Release

platform:
  - x64
  - ARM64

build_script:
  - cmd: scripts\prepare-appveyor.cmd
  - cmake -A %platform% -H. -Bbuild -DLIBDE265_LIBRARY="%APPVEYOR_BUILD_FOLDER%\build-libde265\libde265.lib" -DLIBDE265_INCLUDE_DIR="%APPVEYOR_BUILD_FOLDER%\build-libde265" -DX265_LIBRARY="%APPVEYOR_BUILD_FOLDER%\build-x265\libx265.lib" -DX265_INCLUDE_DIR="%APPVEYOR_BUILD_FOLDER%\build-x265"
  - cmake --build build --config %CONFIGURATION%

artifacts:
  - path: build
