# stats available at
# https://ci.appveyor.com/project/strukturag/libheif
image: Visual Studio 2019

platform:
  - x86
  - x64

configuration: Release

build_script:
  - ps: if($env:PLATFORM -eq "x64") { $env:CMAKE_GEN_SUFFIX=" Win64" }
  - cmd: scripts\prepare-appveyor.cmd
  - cmake -H. -Bbuild -DLIBDE265_LIBRARY="%APPVEYOR_BUILD_FOLDER%\build-libde265\libde265.lib" -DLIBDE265_INCLUDE_DIR="%APPVEYOR_BUILD_FOLDER%\build-libde265" -DX265_LIBRARY="%APPVEYOR_BUILD_FOLDER%\build-x265\libx265.lib" -DX265_INCLUDE_DIR="%APPVEYOR_BUILD_FOLDER%\build-x265"
  - cmake --build build --config %CONFIGURATION%

artifacts:
  - path: build
